# Generated by Django 5.0.6 on 2024-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobnotif',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(max_length=250)),
                ('requirements', models.TextField()),
                ('salary', models.TextField()),
                ('link', models.URLField()),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
