# Generated by Django 5.0.6 on 2024-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotif',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
