# Generated by Django 5.0.6 on 2024-09-13 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_jobnotif_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotif',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
