# Generated by Django 5.0.6 on 2024-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_jobnotif_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotif',
            name='salary',
            field=models.CharField(max_length=250),
        ),
    ]
