# Generated by Django 5.0.6 on 2024-09-18 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_jobnotif_applicants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotif',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
