# Generated by Django 5.0.6 on 2024-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/files/'),
        ),
        migrations.AddField(
            model_name='dcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/'),
        ),
    ]
