# Generated by Django 5.0.6 on 2024-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_alter_account_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rollnumber',
            field=models.CharField(default='21r11a6941', max_length=13),
            preserve_default=False,
        ),
    ]
