# Generated by Django 5.0.6 on 2024-06-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=200)),
                ('article', models.URLField()),
                ('course', models.URLField()),
                ('order', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='notes.jobs')),
            ],
        ),
    ]
