# Generated by Django 5.0.6 on 2024-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='desc',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
