# Generated by Django 5.0.6 on 2024-09-18 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_jobs_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
