# Generated by Django 5.0.6 on 2024-05-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='describe',
            new_name='description',
        ),
    ]
