# Generated by Django 5.0.6 on 2024-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_describe_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='contact',
            name='suggestions',
            field=models.CharField(max_length=500),
        ),
    ]
