# Generated by Django 5.0.6 on 2024-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profileid_bio_profileid_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileid',
            name='git',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profileid',
            name='leetcode',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profileid',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
