# Generated by Django 5.0.6 on 2024-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profileid_git_profileid_leetcode_profileid_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileid',
            name='jobs',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
