# Generated by Django 5.0.6 on 2024-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_likes'),
        ('home', '0005_alter_profileid_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileid',
            name='bookmarked_posts',
            field=models.ManyToManyField(related_name='bookmarked_by', to='blog.post'),
        ),
    ]
